apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: yolo
spec:
  type: LoadBalancer
  loadBalancerIP: 136.116.211.220
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


